// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoTw3QhGHE_iuhmj5j17Jlx_-nQCfLGIQ',
    appId: '1:757551340482:web:f7b3ac02eb7caedc95d45b',
    messagingSenderId: '757551340482',
    projectId: 'frist-app-nd',
    authDomain: 'frist-app-nd.firebaseapp.com',
    storageBucket: 'frist-app-nd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTZcwHQMbxnhCuCXAzDFZCdMjYgGpvKM',
    appId: '1:757551340482:android:2d8120f6d0d4057f95d45b',
    messagingSenderId: '757551340482',
    projectId: 'frist-app-nd',
    storageBucket: 'frist-app-nd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVHwyNHHQBhZRPGlDkV2jOT5cp6uv9pEM',
    appId: '1:757551340482:ios:48429669f2b7de6495d45b',
    messagingSenderId: '757551340482',
    projectId: 'frist-app-nd',
    storageBucket: 'frist-app-nd.appspot.com',
    iosBundleId: 'com.example.firstPp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVHwyNHHQBhZRPGlDkV2jOT5cp6uv9pEM',
    appId: '1:757551340482:ios:c36b4cb17b1d37cd95d45b',
    messagingSenderId: '757551340482',
    projectId: 'frist-app-nd',
    storageBucket: 'frist-app-nd.appspot.com',
    iosBundleId: 'com.example.firstPp.RunnerTests',
  );
}
